### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by NischalDawadi** [Wraient/buttercup#1]
![image](https://github.com/user-attachments/assets/5773d4a9-6721-4334-905c-4ff097920990)

**Comment by Wraient** [comment]
The metadata of the torrent you are trying to open is not been able to download. try selecting a diffrent torrent with more seeders

**Comment by NischalDawadi** [comment]
isn't the list sorted by seeders.. No shows work.

**Comment by Wraient** [comment]
yes the list is sorted by seeders. That sounds like a problem can you confirm your jackett instance is running by going to http://localhost:9117 if you installed it buttercup, if you have a discord we can troubleshoot this faster.

**Comment by NischalDawadi** [comment]
the jackett instance is running

**Comment by Wraient** [comment]
You can see it in the error, that some other process is using port `42069`, you might need to kill that process or change your jackett port

you can find which process is using this port using

```
sudo lsof -i :42069
```

let me know when you find it.

**Comment by Wraient** [comment]
hey, i solved this issue in the latest release, please use the latest release. Ping me if the issue persists.
