### ISSUE TITLE
webtorrent-cli

### ISSUE THREAD

**Issue by ttx99** [Wraient/buttercup#2]
peerflix is not maintained? webtorret-cli instead? 
https://github.com/webtorrent/webtorrent-cli

**Comment by Wraient** [comment]
Thank you for letting me know, i did not know peerflix was not maintained. I will update the script.

**Comment by Wraient** [comment]
[dd5779a](https://github.com/Wraient/buttercup/commit/dd5779a7193f4894dd29c32885c72ec3df333349)
